project:
  type: website
  output-dir: docs

website:
  title: "IRT OM Sensitivity"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: logreg.qmd
        text: Logistic regression and the intercept
      - href: 23pl.qmd
        text: 2PL versus 3PL predictions
